version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vite
    versions:
    - 2.0.0
    - 2.0.0-beta.56
    - 2.0.0-beta.60
    - 2.0.0-beta.61
    - 2.0.0-beta.62
    - 2.0.0-beta.66
    - 2.0.0-beta.69
    - 2.0.0-beta.70
    - 2.0.1
    - 2.0.2
    - 2.0.3
    - 2.0.4
    - 2.1.0
    - 2.1.1
    - 2.1.3
    - 2.1.4
    - 2.1.5
    - 2.2.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.20.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: tailwindcss
    versions:
    - 2.1.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.15.1
    - 4.15.2
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.15.1
    - 4.15.2
    - 4.18.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@vue/compiler-sfc"
    versions:
    - 3.0.10
    - 3.0.6
    - 3.0.7
    - 3.0.9
  - dependency-name: vue
    versions:
    - 3.0.10
    - 3.0.6
    - 3.0.7
    - 3.0.9
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
    - 7.8.0
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
